export const site = {
  origin: "https://www.jiandan.qd.je",
  name: "剪蛋",
  englishName: "Jiandan",
  github: "https://github.com/SKYCHENV/Jiandan",
  release: "https://github.com/SKYCHENV/Jiandan/releases/tag/v1.1.0",
  download: "https://github.com/SKYCHENV/Jiandan/releases/download/v1.1.0/Jiandan.exe",
  version: "1.1.0",
  published: "2026-09-06",
  size: "65,204,099 字节（约 62.2 MiB）",
  sha256: "C74ECAC98178266F2C36B5FEE969396C8597708175C61F61F81F4F7CBD2786B5",
};

export const publicRoutes = [
  "/",
  "/download/",
  "/docs/quick-start/",
  "/docs/compatibility/",
  "/guides/paste-screenshot-jianying/",
  "/workflows/tutorial-videos/",
  "/workflows/graphic-to-video/",
  "/workflows/research-to-content/",
  "/compare/screenshot-import-methods/",
  "/changelog/",
  "/about/",
  "/en/",
  "/en/download/",
  "/en/docs/quick-start/",
];

const common = {
  updated: "2026-09-08",
  image: "/assets/product-demo-frame.png",
};

export const pages = {
  "/download/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "官方下载",
    title: "下载剪蛋 Jiandan v1.1.0",
    description: "从官方 GitHub 下载剪蛋 Windows 版，核对版本、文件大小和 SHA-256，并了解登录与首次启动要求。",
    summary: "Windows 10/11 可用。EXE 已包含运行环境，双击即可启动；首次使用需要邮箱验证码登录。",
    cta: "下载 Jiandan.exe",
    ctaHref: site.download,
    secondary: "查看 GitHub Release",
    secondaryHref: site.release,
    sections: [
      {heading: "发布信息", facts: [
        ["版本", `v${site.version}`], ["发布日期", site.published], ["文件", "Jiandan.exe"], ["大小", site.size],
        ["SHA-256", site.sha256], ["发布源", "SKYCHENV/Jiandan 官方 GitHub Release"],
      ]},
      {heading: "开始之前", paragraphs: [
        "剪蛋面向 Windows 10、Windows 11 与剪映专业版。当前公开版本没有宣称支持 macOS、移动端或 CapCut Desktop。",
        "首次使用需要输入邮箱验证码。登录凭据使用 Windows DPAPI 加密后保存在当前 Windows 用户下，可保持登录 30 天；同一邮箱在新设备登录后，旧设备会自动退出。",
      ]},
      {heading: "安全核对", paragraphs: [
        "请只从本页指向的官方 GitHub Release 获取安装包。下载后可在 PowerShell 中运行下面的命令核对文件：",
      ], code: "Get-FileHash .\\Jiandan.exe -Algorithm SHA256", notes: [
        "输出应与本页 SHA-256 完全一致。", "代码仓库公开可查看，但当前仓库未提供可识别的软件许可证；不要据此推断再分发或商用授权。",
      ]},
    ],
    related: [["第一次使用", "/docs/quick-start/"], ["兼容性与限制", "/docs/compatibility/"], ["查看更新记录", "/changelog/"]],
  },
  "/docs/quick-start/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "快速开始",
    title: "把一张截图粘贴到剪映",
    description: "剪蛋快速开始：启动、截图、回到剪映素材页按 Ctrl+V，让图片进入素材区和播放头位置。",
    summary: "准备好剪蛋和一个剪映草稿，跟着这五步完成第一次图片粘贴。",
    cta: "下载 Windows 版",
    ctaHref: "/download/",
    sections: [
      {heading: "五步完成", steps: [
        ["1", "启动剪蛋", "双击 Jiandan.exe。首次使用完成邮箱验证码登录，看到状态为“已开启”。"],
        ["2", "打开剪映草稿", "进入剪映专业版的草稿，并停留在“素材”页面。"],
        ["3", "截图或复制图片", "使用 Windows 截图工具，或在其他应用中复制一张图片。"],
        ["4", "回到剪映按 Ctrl+V", "只有剪映位于前台且剪贴板里是图片时，剪蛋才会接管这次粘贴。"],
        ["5", "继续编辑", "图片会进入素材区，并通过剪映自身的添加命令落到播放头位置和现有画面轨道上方。"],
      ]},
      {heading: "没有反应时", notes: [
        "确认剪蛋状态窗口显示“已开启”。", "确认当前前台窗口是剪映，且位于素材页面。", "重新复制图片；文字、文件路径或其他剪贴板内容不会触发图片导入。", "剪映界面更新可能影响自动化流程，可在官方 GitHub Issues 附上版本与日志反馈。",
      ]},
      {heading: "不会被接管的粘贴", paragraphs: ["在其他应用中粘贴，或剪贴板内容是文字时，剪蛋应保留系统原来的 Ctrl+V 行为。剪蛋不会把图片或剪贴板内容上传到服务端。"]},
    ],
    related: [["深入理解工作方式", "/guides/paste-screenshot-jianying/"], ["兼容性与限制", "/docs/compatibility/"]],
  },
  "/docs/compatibility/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "兼容性",
    title: "支持范围与已知限制",
    description: "查看剪蛋 v1.1.0 的 Windows、剪映专业版、登录、剪贴板类型和已知限制。",
    summary: "以下信息适用于 2026-09-08 核对的 v1.1.0。未列出的平台不代表兼容。",
    sections: [
      {heading: "已确认范围", facts: [["操作系统", "Windows 10、Windows 11"], ["目标应用", "剪映专业版"], ["输入", "系统截图或剪贴板图片"], ["触发方式", "剪映前台、素材页内按 Ctrl+V"], ["登录", "邮箱验证码；会话最长保持 30 天；单设备登录"], ["图片网络行为", "图片和剪贴板内容不上传"]]},
      {heading: "当前未承诺", notes: ["macOS、iOS、Android。", "CapCut Desktop 或剪映移动版。", "文字、视频、音频、文件列表等非图片剪贴板内容。", "在剪映任意页面、任意版本与任意界面布局下都能工作。", "完全离线启动；登录和会话校验需要联网。"]},
      {heading: "为何版本更新可能有影响", paragraphs: ["剪蛋使用剪映原生导入与素材卡添加命令完成流程。剪映界面或控件结构改变时，既有识别流程可能需要适配。遇到问题请同时记录 Windows 版本、剪映版本、剪蛋版本和复现步骤。"]},
    ],
    related: [["快速开始", "/docs/quick-start/"], ["官方发布页", site.release]],
  },
  "/guides/paste-screenshot-jianying/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "核心教程",
    title: "剪映不能直接粘贴截图？这样把剪贴板图片变成素材",
    description: "解释剪映截图导入的手动流程，以及如何用剪蛋把系统截图或剪贴板图片直接粘贴进剪映素材区和时间线。",
    summary: "剪映专业版不能像聊天窗口一样直接接收刚截好的图片。剪蛋补上的是“剪贴板图片到剪映素材”的这一小段工作流。",
    cta: "查看快速开始",
    ctaHref: "/docs/quick-start/",
    sections: [
      {heading: "为什么会多出几步", paragraphs: ["常见做法是先把截图保存到文件，再打开剪映导入，找到文件，最后把素材放到时间线。另一种做法是先把截图粘进聊天窗口或图片工具，再保存到本地。问题不在截图，而在剪贴板图片和剪映导入之间缺少直接入口。"]},
      {heading: "剪蛋做了什么", steps: [
        ["1", "识别", "只在剪映位于前台、剪贴板包含图片时响应 Ctrl+V。"],
        ["2", "隔离", "将这一次图片保存到独立短路径，避免重复导入以前的截图。"],
        ["3", "导入", "调用剪映原生导入流程，把本次图片精确送入素材区。"],
        ["4", "落位", "调用素材卡自身的添加命令，由剪映决定播放头位置与上方轨道。"],
      ]},
      {heading: "什么时候不适合", notes: ["你使用的不是 Windows 或剪映专业版。", "你要粘贴的是文字、视频或文件，而不是图片。", "你只偶尔导入一张已有本地文件，剪映原生导入已经足够。"]},
    ],
    related: [["比较三种导入方法", "/compare/screenshot-import-methods/"], ["下载剪蛋", "/download/"]],
  },
  "/workflows/tutorial-videos/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "工作流",
    title: "做软件教程时，连续截图如何更快进入剪映",
    description: "面向软件教程与知识讲解创作者的截图取材工作流：截图、标记、粘贴到剪映，再完成讲解视频。",
    summary: "教程视频经常要从网页、软件界面和设置页取多张图。剪蛋负责缩短每张图片进入剪映的路径，剪辑和标注仍在你的创作工具中完成。",
    sections: [
      {heading: "一条可复现的流程", steps: [["1", "先写镜头清单", "按讲解顺序列出需要展示的界面，避免无目的截图。"], ["2", "逐张截图", "隐藏邮箱、通知和账号信息；需要标注时先在截图工具中完成。"], ["3", "粘贴到剪映", "回到素材页按 Ctrl+V，让图片进入当前播放头附近。"], ["4", "完成节奏", "调整图片时长、缩放、旁白和字幕；剪蛋不替代这些剪辑工作。"]]},
      {heading: "适合的内容", notes: ["软件功能教程与设置指南。", "网页产品演示和流程讲解。", "课程、知识点和操作步骤复盘。"]},
      {heading: "素材安全", paragraphs: ["截图前检查个人资料、Cookie、密钥、聊天记录和后台数据。公开发布前再次逐帧查看。剪蛋不会替你识别或遮挡敏感信息。"]},
    ],
    related: [["快速开始", "/docs/quick-start/"], ["资料到内容工作流", "/workflows/research-to-content/"]],
  },
  "/workflows/graphic-to-video/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "工作流",
    title: "把图文卡片复用成剪映视频素材",
    description: "将自己制作或获得授权的图文卡片作为图片素材送入剪映，制作讲解视频或图文视频。",
    summary: "剪蛋不是图文排版或自动成片工具。它适合把已经完成的图文卡片、长图局部和封面方案更顺手地带入剪映。",
    sections: [
      {heading: "从图文到视频", steps: [["1", "整理资产", "确认卡片由你创作或已获得使用授权，并保留原始高分辨率文件。"], ["2", "按镜头截取", "根据竖屏或横屏画幅截取要讲解的局部。"], ["3", "粘贴进剪映", "按讲解顺序把图片送进素材区和时间线。"], ["4", "完成视频表达", "在剪映中设置构图、时长、转场、旁白与字幕。"]]},
      {heading: "剪蛋负责什么", paragraphs: ["它只负责剪贴板图片到剪映之间的转运。内容策划、图文设计、版权判断、视频排版和导出仍由对应工具与创作者完成。"]},
      {heading: "避免误用", notes: ["不要把未经许可的笔记或图片直接做成自己的内容。", "不要把低清截图当作原始设计文件。", "需要透明背景、色彩管理或印刷输出时，应回到专业图像工具处理。"]},
    ],
    related: [["截图到剪映教程", "/guides/paste-screenshot-jianying/"], ["下载剪蛋", "/download/"]],
  },
  "/workflows/research-to-content/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "工作流",
    title: "把调研截图整理成讲解视频，而不是堆满素材库",
    description: "从资料检索、来源记录、合规截图到剪映讲解视频的工作流，说明剪蛋在图片转运环节的作用。",
    summary: "资料型内容的关键不是截得快，而是保留来源、筛选证据并把每张图放在正确的叙事位置。",
    sections: [
      {heading: "建议流程", steps: [["1", "先保存来源", "记录页面标题、URL、作者与访问日期，再决定是否截图。"], ["2", "只截必要证据", "保留足以支撑观点的范围，不泄露账号或付费内容。"], ["3", "按脚本粘贴", "在剪映播放头按顺序加入截图，减少导入窗口和文件夹切换。"], ["4", "在成片标注", "给关键资料添加来源文字，并在简介提供可访问链接。"]]},
      {heading: "边界", paragraphs: ["剪蛋不是收藏夹、知识库、引用管理器或事实核查工具。它不会替你判断网页内容是否真实，也不会自动生成来源标注。"]},
      {heading: "适用方向", notes: ["产品评测与功能对比。", "热点背景和资料梳理。", "课程、论文或报告的可视化讲解。"]},
    ],
    related: [["软件教程工作流", "/workflows/tutorial-videos/"], ["方法比较", "/compare/screenshot-import-methods/"]],
  },
  "/compare/screenshot-import-methods/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "方法比较",
    title: "截图导入剪映：保存文件、聊天窗口中转，还是直接粘贴",
    description: "客观比较截图保存后导入、聊天窗口中转和使用剪蛋粘贴三种剪映图片素材工作流。",
    summary: "没有一种方法适合所有情况。区别主要在于是否需要保留原文件、是否批量整理，以及你导入截图的频率。",
    sections: [
      {heading: "三种方法", table: {headers: ["方法", "更适合", "代价或限制"], rows: [["保存文件后导入", "需要长期归档、重命名或批量管理", "步骤多，但文件组织最清楚"], ["聊天/图片工具中转", "临时没有更直接的入口", "多一次应用切换，容易混入压缩或隐私内容"], ["剪蛋直接粘贴", "连续把截图用于剪映创作", "需要 Windows、剪映专业版、登录和前台素材页"]]}},
      {heading: "怎么选", notes: ["项目需要可复用原图和严格归档：先保存并命名。", "只是偶尔导入一张已有图片：用剪映原生导入。", "经常从网页或软件界面取图做视频：剪蛋能减少重复转运步骤。"]},
      {heading: "没有虚构的提速数字", paragraphs: ["本页不声称固定节省多少秒。实际收益取决于截图数量、硬盘组织、剪映版本和设备性能。最可靠的判断方式，是用你自己的典型任务分别完成一次。"]},
    ],
    related: [["核心教程", "/guides/paste-screenshot-jianying/"], ["兼容性与限制", "/docs/compatibility/"]],
  },
  "/changelog/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "更新记录",
    title: "剪蛋版本更新",
    description: "查看剪蛋官方版本更新记录、发布日期、功能变化、验证信息与对应的正式下载入口。",
    summary: "本页只记录已在官方 GitHub Release 发布的正式版本。",
    sections: [
      {heading: "v1.1.0 · 2026-09-06", notes: ["加入邮箱验证码登录、本地加密会话与自动续期。", "恢复已有登录后再显示主窗口，避免启动时闪过登录页。", "退出程序仍保持登录；主窗口账户菜单保留退出登录。", "修复登录后的主窗口构建错误和源码版依赖安装恢复。", "图片导入和时间线落位逻辑保持与 8332639 一致。", "发布说明记录：35 项桌面测试、9 项后端测试。"]},
      {heading: "下载与核对", paragraphs: ["固定版本的文件、大小与 SHA-256 见下载页。版本信息以官方 GitHub Release 为最终来源。"]},
    ],
    related: [["下载 v1.1.0", "/download/"], ["GitHub Releases", "https://github.com/SKYCHENV/Jiandan/releases"]],
  },
  "/about/": {
    ...common,
    locale: "zh-CN",
    eyebrow: "关于剪蛋",
    title: "为什么做剪蛋",
    description: "了解剪蛋为什么诞生、它解决的截图到剪映素材转运问题、真实产品边界、公开仓库和反馈入口。",
    summary: "因为剪映不支持把刚截好的图片直接粘贴进素材区，一个原本很短的动作常常变成保存、寻找、导入和拖动。剪蛋就是从这里开始。",
    sections: [
      {heading: "少绕一圈", paragraphs: ["截图已经在剪贴板里，却还要先粘进聊天窗口保存，或在文件夹里命名，再回到剪映导入。剪蛋希望把这段重复转运缩短为：截图、回到剪映、粘贴。"]},
      {heading: "产品原则", notes: ["只在剪映前台且剪贴板为图片时响应，不占用正常文字粘贴。", "图片留在本机，不把剪贴板内容上传。", "使用剪映原生流程完成导入和落位，不把宣传功能写成未验证承诺。"]},
      {heading: "项目与反馈", paragraphs: ["源代码、正式版本和问题反馈集中在 SKYCHENV/Jiandan。当前仓库未提供可识别的软件许可证；如需复制、修改或再分发，请先向维护者确认授权。"]},
    ],
    related: [["打开 GitHub", site.github], ["查看兼容性", "/docs/compatibility/"]],
  },
  "/en/": {
    ...common,
    locale: "en",
    eyebrow: "Jiandan for Windows",
    title: "Paste screenshots into Jianying Pro",
    description: "Jiandan is a Windows utility for pasting screenshots and clipboard images into Jianying Pro without saving each image first.",
    summary: "Capture an image, return to the Jianying media page, and press Ctrl+V. Jiandan moves the image into the media library and asks Jianying to place it at the playhead above the current visual track.",
    cta: "Download for Windows",
    ctaHref: "/en/download/",
    sections: [
      {heading: "What Jiandan solves", paragraphs: ["Jianying Pro does not normally accept a fresh screenshot through the clipboard. The usual workaround is to save the image, find it again, import it, and then add it to the timeline. Jiandan shortens that transfer step."]},
      {heading: "How it works", steps: [["1", "Capture", "Take a Windows screenshot or copy an image."], ["2", "Paste", "With Jianying in front on the Media page, press Ctrl+V."], ["3", "Continue", "The image is imported and placed through Jianying's own media-card action."]]},
      {heading: "Scope", notes: ["Windows 10 and Windows 11.", "Jianying Pro; CapCut Desktop compatibility is not claimed.", "Images only. Text and ordinary clipboard use should remain unchanged.", "Email verification is required on first use; images and clipboard contents are not uploaded."]},
    ],
    related: [["Quick start", "/en/docs/quick-start/"], ["GitHub", site.github], ["中文首页", "/"]],
  },
  "/en/download/": {
    ...common,
    locale: "en",
    eyebrow: "Official download",
    title: "Download Jiandan v1.1.0",
    description: "Download the official Jiandan Windows release and verify its file size and SHA-256 checksum.",
    summary: "The executable includes its runtime. First use requires email verification.",
    cta: "Download Jiandan.exe",
    ctaHref: site.download,
    secondary: "View GitHub Release",
    secondaryHref: site.release,
    sections: [
      {heading: "Release details", facts: [["Version", `v${site.version}`], ["Published", site.published], ["File", "Jiandan.exe"], ["Size", "65,204,099 bytes (about 62.2 MiB)"], ["SHA-256", site.sha256], ["Source", "Official SKYCHENV/Jiandan GitHub Release"]]},
      {heading: "Requirements", notes: ["Windows 10 or Windows 11.", "Jianying Pro.", "An email address for first-use verification.", "This release does not claim macOS, mobile, or CapCut Desktop compatibility."]},
      {heading: "Verify the file", code: "Get-FileHash .\\Jiandan.exe -Algorithm SHA256", paragraphs: ["The command output must match the checksum on this page exactly."]},
    ],
    related: [["English quick start", "/en/docs/quick-start/"], ["中文下载页", "/download/"]],
  },
  "/en/docs/quick-start/": {
    ...common,
    locale: "en",
    eyebrow: "Quick start",
    title: "Paste your first screenshot into Jianying",
    description: "Start Jiandan, capture an image, and paste it into the Jianying Pro media page in five steps.",
    summary: "This guide applies to Jiandan v1.1.0 on Windows 10/11 and was checked on 2026-09-08.",
    cta: "Download Jiandan",
    ctaHref: "/en/download/",
    sections: [
      {heading: "Five steps", steps: [["1", "Start Jiandan", "Open Jiandan.exe and complete email verification on first use."], ["2", "Open a draft", "Open Jianying Pro and stay on the Media page."], ["3", "Capture", "Take a Windows screenshot or copy an image."], ["4", "Paste", "Return to Jianying and press Ctrl+V."], ["5", "Edit", "The image enters the media library and is placed at the playhead above the existing visual track."]]},
      {heading: "If nothing happens", notes: ["Confirm that Jiandan says it is enabled.", "Confirm that Jianying is the foreground app and the Media page is open.", "Copy the image again; text and non-image clipboard content do not trigger import.", "Report reproducible UI changes through GitHub Issues."]},
    ],
    related: [["English home", "/en/"], ["Compatibility in Chinese", "/docs/compatibility/"]],
  },
};

export function normalizePath(pathname) {
  if (!pathname || pathname === "/") return "/";
  return `${pathname.replace(/\/+$/u, "")}/`;
}
